# O quê é numpy?

Numpy é um módulo, ou biblioteca, para extender Python, conferindo um tipo _array_ eficiente e operações para esse tipo array.
A vantagem, e o motivo desse módulo ser tão importante além da eficiência, é a praticidade de realizar muitas operções numéricas com muito pouco código.
O interface acessível ao usário é quase tão simples quanto à do Matlab, mas é código aberto, além de possibilitar o uso de todo o resto da linguagem python, que é muito mais poderosa que Matlab. 
Em conjunto com o módulo _matplotlib_, que veremos amanhã, numpy (e scipy de modo geral) são as resposáveis por python ter conquistado espaço no mundo acadêmico.

Vejamos como usar alguns elementos de numpy.

In [1]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = np.array([5,6,7])
d = np.array([[1,-1],[-1,1]])

Sobre o código acima:

```python
import numpy as np
```
está pedindo que o módulo `numpy` seja carregado e que receba o nome `np`.

```python
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = np.array([5,6,7])
d = np.array([[1,-1],[-1,1]])
```
está definindo duas arrays, passando listas como argumentos para a função `np.array`.

Para saber qual a dimensão de uma array, use o atributo `shape`:

In [2]:
a

array([1, 2, 3, 4])

In [3]:
a.shape

(4,)

In [4]:
b

array([10, 20, 30, 40])

In [5]:
b.shape

(4,)

In [6]:
d

array([[ 1, -1],
       [-1,  1]])

In [7]:
d.shape

(2, 2)

Note que `d` é uma array bidimensional e que o tipo array possibilita a criação de array de alta dimensão:

In [8]:
foo = np.ones((3,3,3,3,3,3,3))
foo.shape

(3, 3, 3, 3, 3, 3, 3)

Para arrays bidimensionais, a transposição de linhas e colunas é possível usando o atributo `T`:

In [9]:
foo = np.array([[1,2],[3,4]])
print(f'{foo} <- foo\n\n{foo.T} <- foo.T')

[[1 2]
 [3 4]] <- foo

[[1 3]
 [2 4]] <- foo.T


Note que arrays unidimensionais são imunes à transoposição

In [10]:
print(f'{a} <- a\n\n{a.T} <- a.T')

[1 2 3 4] <- a

[1 2 3 4] <- a.T


mas arrays bidimensioais do tipo linha ou coluna não

In [11]:
foo = np.array([[1,2,3,4,5]])
print(f'{foo} <- foo\n\n{foo.T} <- foo.T')

[[1 2 3 4 5]] <- foo

[[1]
 [2]
 [3]
 [4]
 [5]] <- foo.T


Saber o shape de uma array é importante para fazer aritmética:

In [12]:
# soma de duas arrays com mesmo shape
# note que a e b têm shape (4,) e a soma a + b também tem shape (4,)
# a soma é feita elemento a elemento
print(f"""
a = {a}
b = {b}
a + b = {a + b}
""")
(a + b).shape


a = [1 2 3 4]
b = [10 20 30 40]
a + b = [11 22 33 44]



(4,)

In [13]:
# produto de duas array com mesmo shape
# note que a e b têm shape (4,) e o produto a * b também tem shape (4,)
# o produto é feito elemento a elemento
print(f"""
a = {a}
b = {b}
a * b = {a * b}
""")
(a * b).shape


a = [1 2 3 4]
b = [10 20 30 40]
a * b = [ 10  40  90 160]



(4,)

In [14]:
# soma e produto de escalares com arrays
# essas operações acontecem em cada elemento da array
print(f"""
a = {a}
3 + a = {3 + a}
5 * a = {5 * a}
""")
(3 + b).shape, (5 * a).shape


a = [1 2 3 4]
3 + a = [4 5 6 7]
5 * a = [ 5 10 15 20]



((4,), (4,))

In [15]:
# de modo geral, operações entre escalar e array aconteces acontecem e cada elemento da array
print(f"""
a = {a}
a / 2 = {a /2}
a ** 2 = {a ** 2}
np.sin(a) = {np.sin(a)}
""")


a = [1 2 3 4]
a / 2 = [ 0.5  1.   1.5  2. ]
a ** 2 = [ 1  4  9 16]
np.sin(a) = [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]



Esses exemplos são casos de _broadcasting_, termo usado para significar que um elemento de dimensão menor é "repetido" de forma a coincidir com a dimensão maior para que a operação possa ser feita elemento a elemento.
Além dos casos acima, é possível fazer essas operações com arrays uni e bidimensionais com shape a de shapes adequados

In [16]:
foo = np.array([1,2,3])
bar = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(foo + bar, foo + bar.T, sep='\n\n')

[[2 3 4]
 [3 4 5]
 [4 5 6]]

[[2 4 6]
 [2 4 6]
 [2 4 6]]


É possível fazer o produto interno de duas arrays de mesmo shape

In [17]:
a.dot(b), a @ b

(300, 300)

Ou o produto de matrizes entre arrays de shape apropriado:

In [18]:
foo = np.array([[1,-1],[-1,1]])
bar = np.array([2,20])
foo.dot(bar), foo @ bar

(array([-18,  18]), array([-18,  18]))

O tipo arrays tem muitos métodos convenientes para operar sobre os valores como méadia, variância, máximo e mínimo, por exemplo.

In [19]:
# média
a.mean()

2.5

In [20]:
# variância
a.var()

1.25

In [21]:
# mínimo e máximo
a.min(), a.max()

(1, 4)

Além dos métodos, diversas funções matemáticas capazes de lidar com arrays são acessíveis imediatamente

In [22]:
# seno, cosseno, tangente
np.sin(a), np.cos(a), np.tan(a)

(array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]),
 array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362]),
 array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128]))

In [23]:
# funções arco
np.arcsin(a), np.arccos(a),  np.arctan(a)

/usr/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in arcsin
  from ipykernel import kernelapp as app
/usr/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app


(array([ 1.57079633,         nan,         nan,         nan]),
 array([  0.,  nan,  nan,  nan]),
 array([ 0.78539816,  1.10714872,  1.24904577,  1.32581766]))

e diversas outras.

Além do tipo array e das operações sobre elementos desse tipo, numpy traz uma coleção de submódulos temáticos muito úteis.
Dois muito úteis são o de algebra linear, chamado `numpy.linalg`, e o de números aleatórios, chamado `numpy.random`.
Vejamos o nome algumas das funções nesse submódulos:

In [24]:
from numpy.linalg import norm, qr, cholesky, det, inv
from numpy.random import rand, randn, choice, randint, gamma, normal

## Um pouco sobre "Indexação Chique" (Fancy Indexing)

Embora o objetivo do numpy seja reduzir ao máximo a necessidade de acessar elementos em arrays, favorecendo um estilo de solução de problemas em computação conhecido como _vetorização_, muitas vezes é necessário acessar um subconjunto de elementos de arrays.
Há algumas formas de se fazer isso, com algumas sutilezas envolvidas (embora tais sutilezas sejam relevantes apenas do ponto de vista da eficiência).

Vejamos alguns exemplos:

In [33]:
a = np.arange(20).reshape((4,5))
b = a.tolist()
print(f"""
a = 
{a}

b = 
{b}
""")


a = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

b = 
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]



Note que a array `a` tem shape `(4,5)`, de modo que, assim como com listas e outros container builtin de python, o primeira linha tem índice `0` e a última linha tem índice `4-1 = 3`.
Analogamente, a primeira coluna tem índice `0` e a última tem índice `5-1 = 4`.

Podemos acessar apenas linhas da array `a`do mesmo modo que faríamos com a lista de listas `b`:

In [34]:
a[2]

array([10, 11, 12, 13, 14])

In [35]:
b[2]

[10, 11, 12, 13, 14]

e podemos acessar um elemento de uma linha da mesma forma

In [36]:
a[2][1]

11

In [37]:
b[2][1]

11

Porém, o tipo array permite fazer essa operação de modo mais simples, enquanto uma lista de listas não

In [38]:
a[2,1]

11

In [39]:
b[2,1]

TypeError: list indices must be integers or slices, not tuple

Tanto arrays quanto listas permitem o uso de "slices",cuja a forma é `começo:fim:intervalo`, como índices para capturar porções maiores que um elemento:

In [41]:
a[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
b[0:2]

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

usando "slices" é possível omitir o zero ou ou último índice, ou seja, a mesma operação acima pode ser escrita de forma equivalente

In [43]:
a[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

e as seguintes operações também são equivalentes

In [46]:
a[1:4]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
a[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Combinando a regrinha acima, um sinal de dois pontos, `:`, sozinho significa todos os elementos daquela dimensão:

In [47]:
a[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Com isso é possível e a sintaxe simplificada de arrays para acessar colunas, é possível pegar uma coluna inteira.
O exemplo a seguir pode ser lido como "pegue todas as linhas da coluna 2 (terceira coluna contando do zero)" 

In [49]:
a[:,2]

array([ 2,  7, 12, 17])

Esses conceitos se generalizam pra qualquer shape:

In [51]:
b = np.arange(27).reshape((3,3,3))
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
b[0,:,1]

array([1, 4, 7])

Além dos "slices" também é possível usar elípses, significando "todas as demais dimensões", conceito que é útil quand as arrays tem shapes:

In [53]:
b[0,...]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Outra forma de indexar arrays (ou listas) é usando listas ou arrays de índices.
O exemplos seguintes são equivalentes (a menos do tipo devolvido):

In [60]:
a[0,2], a[1,3]

(2, 8)

In [61]:
a[[0,1],[2,3]]

array([2, 8])

Todos esses médodos podem ser combinado e algumas bibliotecas, como pandas, ampliam esse mecanismo permitindo indexação por valores nomes de colunas e outros possíveis valores que poderiam indexar uma tabela.

# Scipy

Scipy é um módulo que contém o numpy e outros módulos temáticos, todos orientados para a aplicação em problemas típicamente cietíficos.

In [25]:
from scipy.optimize import fixed_point, minimize
from scipy.special import erf, erfc, beta, gamma, hermite
from scipy.integrate import quad, quadrature, ode, odeint