# O quê é numpy?

Numpy é um módulo, ou biblioteca, para extender Python, conferindo um tipo _array_ eficiente e operações para esse tipo array.
A vantagem, e o motivo desse módulo ser tão importante além da eficiência, é a praticidade de realizar muitas operções numéricas com muito pouco código.
O interface acessível ao usário é quase tão simples quanto à do Matlab, mas é código aberto, além de possibilitar o uso de todo o resto da linguagem python, que é muito mais poderosa que Matlab. 
Em conjunto com o módulo _matplotlib_, que veremos amanhã, numpy (e scipy de modo geral) são as resposáveis por python ter conquistado espaço no mundo acadêmico.

Vejamos como usar alguns elementos de numpy.

In [37]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = np.array([5,6,7])
d = np.array([[1,-1],[-1,1]])

Sobre o código acima:

```python
import numpy as np
```
está pedindo que o módulo `numpy` seja carregado e que receba o nome `np`.

```python
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = np.array([5,6,7])
d = np.array([[1,-1],[-1,1]])
```
está definindo duas arrays, passando listas como argumentos para a função `np.array`.

Para saber qual a dimensão de uma array, use o atributo `shape`:

In [38]:
a

array([1, 2, 3, 4])

In [39]:
a.shape

(4,)

In [40]:
b

array([10, 20, 30, 40])

In [41]:
b.shape

(4,)

In [42]:
d

array([[ 1, -1],
       [-1,  1]])

In [43]:
d.shape

(2, 2)

Note que `d` é uma array bidimensional e que o tipo array possibilita a criação de array de alta dimensão:

In [44]:
foo = np.ones((3,3,3,3,3,3,3))
foo.shape

(3, 3, 3, 3, 3, 3, 3)

Para arrays bidimensionais, a transposição de linhas e colunas é possível usando o atributo `T`:

In [45]:
foo = np.array([[1,2],[3,4]])
print(f'{foo} <- foo\n\n{foo.T} <- foo.T')

[[1 2]
 [3 4]] <- foo

[[1 3]
 [2 4]] <- foo.T


Note que arrays unidimensionais são imunes à transoposição

In [54]:
print(f'{a} <- a\n\n{a.T} <- a.T')

[1 2 3 4] <- a

[1 2 3 4] <- a.T


mas arrays bidimensioais do tipo linha ou coluna não

In [55]:
foo = np.array([[1,2,3,4,5]])
print(f'{foo} <- foo\n\n{foo.T} <- foo.T')

[[1 2 3 4 5]] <- foo

[[1]
 [2]
 [3]
 [4]
 [5]] <- foo.T


Saber o shape de uma array é importante para fazer aritmética:

In [48]:
# soma de duas arrays com mesmo shape
# note que a e b têm shape (4,) e a soma a + b também tem shape (4,)
# a soma é feita elemento a elemento
print(f"""
a = {a}
b = {b}
a + b = {a + b}
""")
(a + b).shape


a = [1 2 3 4]
b = [10 20 30 40]
a + b = [11 22 33 44]



(4,)

In [49]:
# produto de duas array com mesmo shape
# note que a e b têm shape (4,) e o produto a * b também tem shape (4,)
# o produto é feito elemento a elemento
print(f"""
a = {a}
b = {b}
a * b = {a * b}
""")
(a * b).shape


a = [1 2 3 4]
b = [10 20 30 40]
a * b = [ 10  40  90 160]



(4,)

In [51]:
# soma e produto de escalares com arrays
# essas operações acontecem em cada elemento da array
print(f"""
a = {a}
3 + a = {3 + a}
5 * a = {5 * a}
""")
(3 + b).shape, (5 * a).shape


a = [1 2 3 4]
3 + a = [4 5 6 7]
5 * a = [ 5 10 15 20]



((4,), (4,))

In [52]:
# de modo geral, operações entre escalar e array aconteces acontecem e cada elemento da array
print(f"""
a = {a}
a / 2 = {a /2}
a ** 2 = {a ** 2}
np.sin(a) = {np.sin(a)}
""")


a = [1 2 3 4]
a / 2 = [ 0.5  1.   1.5  2. ]
a ** 2 = [ 1  4  9 16]
np.sin(a) = [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]



Esses exemplos são casos de _broadcasting_, termo usado para significar que um elemento de dimensão menor é "repetido" de forma a coincidir com a dimensão maior para que a operação possa ser feita elemento a elemento.
Além dos casos acima, é possível fazer essas operações com arrays uni e bidimensionais com shape a de shapes adequados

In [69]:
foo = np.array([1,2,3])
bar = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(foo + bar, foo + bar.T, sep='\n\n')

[[2 3 4]
 [3 4 5]
 [4 5 6]]

[[2 4 6]
 [2 4 6]
 [2 4 6]]


É possível fazer o produto interno de duas arrays de mesmo shape

In [57]:
a.dot(b), a @ b

(300, 300)

Ou o produto de matrizes entre arrays de shape apropriado:

In [59]:
foo = np.array([[1,-1],[-1,1]])
bar = np.array([2,20])
foo.dot(bar), foo @ bar

(array([-18,  18]), array([-18,  18]))

O tipo arrays tem muitos métodos convenientes para operar sobre os valores como méadia, variância, máximo e mínimo, por exemplo.

In [62]:
# média
a.mean()

2.5

In [63]:
# variância
a.var()

1.25

In [64]:
# mínimo e máximo
a.min(), a.max()

(1, 4)

Além dos métodos, diversas funções matemáticas capazes de lidar com arrays são acessíveis imediatamente

In [70]:
# seno, cosseno, tangente
np.sin(a), np.cos(a), np.tan(a)

(array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]),
 array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362]),
 array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128]))

In [72]:
# funções arco
np.arcsin(a), np.arccos(a),  np.arctan(a)

/usr/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in arcsin
  from ipykernel import kernelapp as app
/usr/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app


(array([ 1.57079633,         nan,         nan,         nan]),
 array([  0.,  nan,  nan,  nan]),
 array([ 0.78539816,  1.10714872,  1.24904577,  1.32581766]))

e diversas outras.

Além do tipo array e das operações sobre elementos desse tipo, numpy traz uma coleção de submódulos temáticos muito úteis.
Dois muito úteis são o de algebra linear, chamado `numpy.linalg`, e o de números aleatórios, chamado `numpy.random`.
Vejamos o nome algumas das funções nesse submódulos:

In [74]:
from numpy.linalg import norm, qr, cholesky, det, inv
from numpy.random import rand, randn, choice, randint, gamma, normal

# Scipy

Scipy é um módulo que contém o numpy e outros módulos temáticos, todos orientados para a aplicação em problemas típicamente cietíficos.

In [79]:
from scipy.optimize import fixed_point, minimize
from scipy.special import erf, erfc, beta, gamma, hermite
from scipy.integrate import quad, quadrature, ode, odeint